version: '3.7'

services:
  fastapi:
    container_name: fastapi-user # change container name as per project
    build: .
    command: uvicorn main:app --reload --port=8000 --host=0.0.0.0
    env_file:
      - ./env/.env
    ports:
      - 10:8000
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    container_name: fastapi-userdb # change container name as per project
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.db.env
    ports:
      - 5433:5432
    expose:
      - 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: